import { test, expect, settings, closePanel, createLegacy, reading } from './fixtures';
import type { Discussion } from '../src/domain';

test('focused confirmation, reply drafts, manual boundaries, automatic overall completion and reading preferences', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  const id = await createLegacy(page, { input: { topic: 'Focused fixture.', goal: 'A decision with conditions.', constraints: 'Use supplied evidence only.' } });
  const state = async (): Promise<Discussion> => (await page.request.get(`/api/discussions/${id}`)).json();
  await expect.poll(async () => (await state()).activity).toBeNull();
  expect((await state()).v2!.calls).toHaveLength(2);
  await expect(page.locator('.focus-current')).toContainText('目前議題');
  await expect(page.locator('.public-details').first()).not.toHaveAttribute('open', '');
  const before = await state();
  await page.getByRole('button', { name: '查看議題' }).click();
  const unchangedSettings = page.waitForResponse(r => r.url().endsWith(`/api/discussions/${id}`) && r.request().method() === 'PATCH');
  await page.getByRole('button', { name: '更新目標與限制' }).click();
  expect((await unchangedSettings).status()).toBe(200);
  expect(await state()).toEqual(before);
  await page.locator('.issues-panel > summary').click();
  await page.locator('.message.codex').first().getByRole('button', { name: '引用追問' }).click();
  await expect(page.getByLabel('加入討論')).toHaveValue('針對這則訊息：\n');
  expect((await state()).v2!.calls).toHaveLength(2);
  await page.getByLabel('加入討論').fill('Keep the stated evidence condition and verify the answer.');
  await page.getByRole('button', { name: '送出並續談 ↑' }).click();
  await expect.poll(async () => (await state()).v2!.calls.length).toBe(4);
  await expect.poll(async () => (await state()).activity).toBeNull();
  const confirmed = await state();
  expect(confirmed.v2!.issues[0]!.confirmation).not.toBeNull();
  expect(confirmed.v2!.issues[0]!.status).toBe('concluded');
  expect(confirmed.v2!.completed).toBe(false); // Manual boundary preserves the pending whole-discussion confirmation.
  expect(confirmed.messages.findLast(m => m.sender === 'user')!.inReplyTo).toBe(before.messages.find(m => m.sender === 'codex')!.id);
  await settings(page); await page.getByLabel('進行方式').selectOption('auto'); await closePanel(page);
  await page.getByRole('button', { name: '繼續交流', exact: true }).click();
  await expect.poll(async () => (await state()).v2!.completed).toBe(true);
  await expect.poll(async () => (await state()).activity).toBeNull();
  await expect(page.locator('.discussion-notice')).toContainText('整場結果已由雙方明確確認');
  const confirmedOverall = await state();
  await settings(page); await page.getByLabel('顯示名稱').fill('已確認的結果');
  await page.getByRole('button', { name: '儲存名稱' }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('已確認的結果');
  await closePanel(page);
  const final = await state();
  expect(final.v2).toEqual(confirmedOverall.v2); expect(final.messages).toEqual(confirmedOverall.messages);
  await reading(page); await page.getByLabel('閱讀模式').selectOption('full');
  await expect(page.locator('.public-details').first()).toHaveAttribute('open', '');
  await expect(page.locator('.public-details').first()).toContainText('const complete = true;');
  await reading(page); await page.getByLabel('閱讀模式').selectOption('highlights');
  await closePanel(page); await page.locator('.message:not(.user)').last().getByRole('button', { name: '回應來源', exact: true }).click();
  expect(await page.locator('.public-details[open]').count()).toBeGreaterThan(0);
  expect(await state()).toEqual(final);
  expect(await (await page.request.get(`/api/discussions/${id}/export?format=json`)).json()).toEqual(final);
  await reading(page); await page.getByLabel('閱讀模式').selectOption('full');
  await page.reload(); await reading(page); await expect(page.getByLabel('閱讀模式')).toHaveValue('full');
  await expect(page.locator('.discussion-notice')).toContainText('整場結果已由雙方明確確認');
  await expect(page.getByLabel('對話內容')).not.toContainText('<<<CANDC_CONTROL_V2>>>');
  await closePanel(page); await page.screenshot({ path: process.env.CANDC_SCREENSHOT_DIR ? `${process.env.CANDC_SCREENSHOT_DIR}/focused-desktop.png` : '.cache/focused-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: process.env.CANDC_SCREENSHOT_DIR ? `${process.env.CANDC_SCREENSHOT_DIR}/focused-mobile.png` : '.cache/focused-mobile.png' });
  await page.getByRole('button', { name: '查看議題' }).click(); await page.getByRole('button', { name: '查看提議' }).first().click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.locator(`#message-${final.v2!.issues[0]!.proposal!.messageId}`)).toBeFocused();
  expect(errors).toEqual([]);
});

test('unconfirmed saving persists through refresh, recovery does not retry, explicit rebuilding carries budgets', async ({ page }) => {
  const id = await createLegacy(page, { input: { topic: 'Storage recovery fixture.' } });
  const state = async (): Promise<Discussion> => (await page.request.get(`/api/discussions/${id}`)).json();
  await expect.poll(async () => (await state()).activity).toBeNull();
  const before = await state();
  expect((await page.request.post('/__fixture/storage-fault', { data: { stage: 'sync' } })).ok()).toBe(true);
  await page.getByLabel('加入討論').fill('Saving this input must be checked.');
  await page.getByRole('button', { name: '送出並續談 ↑' }).click();
  await expect(page.locator('.discussion-notice')).toContainText('未確認保存');
  await page.reload(); await expect(page.locator('.discussion-notice')).toContainText('未確認保存');
  if (process.env.CANDC_SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.CANDC_SCREENSHOT_DIR}/storage-unconfirmed.png` });
  expect((await state()).v2!.calls).toHaveLength(before.v2!.calls.length);
  await page.getByRole('button', { name: '驗證保存並復原' }).click();
  await expect(page.getByRole('button', { name: '重建工作階段並續談' })).toBeVisible();
  const verified = await state();
  expect(verified.messages.find(m => m.text === 'Saving this input must be checked.')).toBeDefined();
  expect(verified.v2!.calls).toHaveLength(before.v2!.calls.length);
  await page.getByRole('button', { name: '重建工作階段並續談' }).click();
  await expect.poll(async () => (await state()).v2!.calls.length).toBeGreaterThan(before.v2!.calls.length);
  await expect.poll(async () => (await state()).activity).toBeNull();
  const rebuilt = await state();
  expect(rebuilt.v2!.receipts.some(r => r.status === 'retired')).toBe(true);
  expect(rebuilt.v2!.receipts.some(r => r.status === 'valid' && !before.v2!.receipts.some(old => old.generation === r.generation))).toBe(true);
  expect(rebuilt.elapsedMs).toBeGreaterThanOrEqual(before.elapsedMs);
  expect(rebuilt.limits).toEqual(before.limits);
});

test('interruption retains partial output and rebuilds from confirmed history without replaying the failed call', async ({ page }) => {
  const id = await createLegacy(page, { input: { topic: 'Interruption fixture.' } });
  const state = async (): Promise<Discussion> => (await page.request.get(`/api/discussions/${id}`)).json();
  await expect.poll(async () => (await state()).v2!.calls.length).toBeGreaterThan(0);
  await page.getByRole('button', { name: '立即停止' }).click();
  await expect.poll(async () => (await state()).activity).toBeNull();
  const stopped = await state();
  expect(stopped.v2!.calls[0]!.status).toBe('failed');
  await page.reload(); await page.getByRole('button', { name: '重建工作階段並續談' }).click();
  await page.getByRole('button', { name: '本次回覆後暫停' }).click();
  await expect.poll(async () => (await state()).activity, { timeout: 20_000 }).toBeNull();
  const rebuilt = await state();
  expect(rebuilt.v2!.calls[0]!.requestId).toBe(stopped.v2!.calls[0]!.requestId);
  expect(rebuilt.v2!.calls.filter(c => c.requestId === stopped.v2!.calls[0]!.requestId)).toHaveLength(1);
  expect(rebuilt.v2!.calls.at(-1)!.snapshot.messages.every(ref => rebuilt.messages.find(m => m.id === ref.id)?.status === 'completed')).toBe(true);
});
