import { translate } from './i18n.js';
import { PerformancePanel } from './PerformancePanel';
import { useEffect, useState } from 'react';
import { api, durationText, type Discussion } from './api';
const issueStatus = { get pending() { return translate("待討論"); }, get active() { return translate("討論中"); }, get concluded() { return translate("已有結論"); }, get disagreed() { return translate("已釐清分歧"); }, get blocked() { return translate("待補資料"); }, get skipped() { return translate("已略過"); } };
export function jumpToMessage(id: string) {
  const element = document.getElementById(`message-${id}`);
  if (!element) return;
  element.querySelectorAll('details').forEach(detail => { detail.open = true; });
  element.scrollIntoView({ block: 'center', behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' }); element.focus({ preventScroll: true });
}
export function FocusedPanel({ state, busy, perform, section, onJump }: { state: Discussion; busy: boolean; section: 'issues' | 'diagnostics'; onJump: (id: string) => void; perform: (action: () => Promise<unknown>) => Promise<void> }) {
  const [title, setTitle] = useState(''), [goal, setGoal] = useState(state.goal), [constraints, setConstraints] = useState(state.constraints);
  useEffect(() => { setGoal(state.goal); setConstraints(state.constraints); }, [state.goal, state.constraints]);
  const readOnly = state.management !== undefined && state.management.folder !== 'active';
  const locked = readOnly || busy || !!state.storage;
  const v = state.v2!;
  const issueAction = (action: string, issueId?: string, title?: string) => api(`/api/discussions/${state.id}/issues`, 'POST',
    { operationId: crypto.randomUUID(), expectedVersion: v.taskVersion, action, issueId, title });
  return <div className="focus-area">    {section === 'issues' && <details open className="issues-panel"><summary>{translate("議題與確認 ·")}{" "}{v.issues.length}{" "}{translate("題")}</summary><p>{translate("完成提議需要另一方在同議題、同版本確認。略過會保留為結果限制。")}</p>{v.issues.map((issue, index) => <div className={'issue-row' + (issue.id === v.currentIssueId ? ' current' : '')} key={issue.id}><div className="issue-head"><em>{index + 1}</em><strong>{issue.title}</strong><span className={'issue-status ' + issue.status}>{issueStatus[issue.status]}</span><small>v{issue.version}</small></div><div className="actions"><button disabled={locked} onClick={() => void perform(() => issueAction('select', issue.id))}>{translate("選取議題")}</button><button disabled={locked} onClick={() => void perform(() => issueAction('skip', issue.id))}>{translate("略過議題")}</button>{issue.source !== 'user' && <button onClick={() => onJump(issue.source)}>{translate("來源")}</button>}</div>{issue.proposal && <p>{translate("提議")}{" "}{issue.proposal.author} · {issueStatus[issue.proposal.outcome]}{" "}{translate("· 提議 v")}{issue.proposal.version} · {issue.confirmation ? translate("已由 {0} 確認", issue.confirmation.author) : translate("待另一方確認")} <button onClick={() => onJump(issue.proposal!.messageId)}>{translate("查看提議")}</button></p>}{issue.result && <p>{issue.result}</p>}{issue.proposal?.conditions && <p>{translate("適用條件／分歧依據：")}{issue.proposal.conditions}</p>}{issue.unresolved.length > 0 && <p>{translate("未解：")}{issue.unresolved.join('；')}</p>}</div>)}
      <dl className="run-summary"><dt>{translate("已進行")}</dt><dd>{translate("第")}{" "}{state.round} / {state.limits.maxRounds}{" "}{translate("輪")}</dd><dt>{translate("執行時間")}</dt><dd>{durationText(state.elapsedMs)} / {durationText(state.limits.maxDurationMs)}</dd><dt>{translate("單次上限")}</dt><dd>{durationText(state.limits.turnTimeoutMs)}</dd><dt>{translate("執行模式")}</dt><dd>{{ manual: translate("手動"), auto: translate("自動"), conclusion: translate("有結論就停") }[state.mode]} · {state.flow === 'free' ? translate("自由對話") : translate("輪流發言")}</dd></dl>
      <form onSubmit={e => { e.preventDefault(); void perform(async () => { await issueAction('add', crypto.randomUUID(), title); setTitle(''); }); }}><label>{translate("新增待討論議題")}<input disabled={readOnly} aria-label={translate("新增議題")} required maxLength={32000} value={title} onChange={e => setTitle(e.target.value)}/></label><button disabled={locked || !title.trim()}>{translate("加入待討論")}</button></form>
      <form onSubmit={e => { e.preventDefault(); void perform(() => api(`/api/discussions/${state.id}`, 'PATCH', { expectedVersion: v.configurationVersion, goal, constraints })); }}><label>{translate("目前目標")}<textarea disabled={readOnly} aria-label={translate("目前目標")} value={goal} maxLength={32000} onChange={e => setGoal(e.target.value)}/></label><label>{translate("目前限制")}<textarea disabled={readOnly} aria-label={translate("目前限制")} value={constraints} maxLength={32000} onChange={e => setConstraints(e.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={state.focused} disabled={locked} onChange={e => void perform(() => api(`/api/discussions/${state.id}`, 'PATCH', { expectedVersion: v.configurationVersion, focused: e.target.checked }))}/>{translate("聚焦討論")}</label><button disabled={locked}>{translate("更新目標與限制")}</button></form>
      <p>{translate("未處置要求")}</p>{v.requests.filter(r => !['disposed', 'checked'].includes(r.status)).map(r => <div key={r.messageId}><button onClick={() => onJump(r.messageId)}>{translate("查看使用者要求")}</button> · {r.status === 'unmarked' ? translate("未標註") : translate("已標註回應 · 尚待檢查")} {r.reason}<button disabled={locked} onClick={() => void perform(() => issueAction('dispose', r.messageId, 'User marked this request as disposed.'))}>{translate("我已處置此要求")}</button></div>)}
    </details>}
    {section === 'diagnostics' && <PerformancePanel discussionId={state.id}/>}
    {section === 'diagnostics' && <details open><summary>{translate("輸入與呼叫診斷 ·")}{" "}{v.calls.length}{" "}{translate("次")}</summary><p>{translate("曾納入 session 不表示模型完整保有細節。未觀測時間及未回傳 token 用量顯示未知；不推估帳單。無法確認耗時的中斷呼叫，已保守保留")}{" "}{v.uncertainBudgetMs}{" "}{translate("ms 執行預算；這不是觀測耗時。")}</p>{v.receipts.map(r => <p key={r.generation}>{r.agent} · {r.status} · {r.messages.length}{" "}{translate("則已納入 ·")}{" "}{r.evidence.length}{" "}{translate("個來源版本 · 設定 v")}{r.configurationVersion} · {r.sessionId ?? translate("暫定工作階段")}</p>)}{v.calls.map(call => <details key={call.requestId}><summary>{call.agent} · {call.status} · {call.diagnostics.input.characters.toLocaleString()}{" "}{translate("字元 · 控制")}{" "}{call.control ?? translate("未確認")}</summary><p>{translate("回應標註：")}{call.annotation}{" "}{translate("· 回應對象")}{" "}{call.snapshot.responseTarget ? <button onClick={() => onJump(call.snapshot.responseTarget!)}>{translate("來源訊息")}</button> : translate("無")}</p><pre>{JSON.stringify({ requestId: call.requestId, generation: call.snapshot.generation, resolvedModel: call.resolvedModel, input: call.diagnostics.input,
        timings: call.diagnostics.timings, usage: call.diagnostics.usage ?? 'unknown', failureStage: call.diagnostics.failureStage }, null, 2)}</pre></details>)}</details>}
  </div>;
}
