import { PerformancePanel } from './PerformancePanel';
import { useEffect, useState } from 'react';
import { api, durationText, type Discussion } from './api';
const issueStatus = { pending: '待討論', active: '討論中', concluded: '已有結論', disagreed: '已釐清分歧', blocked: '待補資料', skipped: '已略過' };
export function jumpToMessage(id: string) {
  const element = document.getElementById(`message-${id}`);
  if (!element) return;
  element.querySelectorAll('details').forEach(detail => { detail.open = true; });
  element.scrollIntoView({ block: 'center', behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' }); element.focus({ preventScroll: true });
}
export function FocusedPanel({ state, busy, perform, section, onJump }: { state: Discussion; busy: boolean; section: 'issues' | 'diagnostics'; onJump: (id: string) => void; perform: (action: () => Promise<unknown>) => Promise<void> }) {
  const [title, setTitle] = useState(''), [goal, setGoal] = useState(state.goal), [constraints, setConstraints] = useState(state.constraints);
  useEffect(() => { setGoal(state.goal); setConstraints(state.constraints); }, [state.goal, state.constraints]);
  const v = state.v2!;
  const issueAction = (action: string, issueId?: string, title?: string) => api(`/api/discussions/${state.id}/issues`, 'POST',
    { operationId: crypto.randomUUID(), expectedVersion: v.taskVersion, action, issueId, title });
  return <div className="focus-area">    {section === 'issues' && <details open className="issues-panel"><summary>議題與確認 · {v.issues.length} 題</summary><p>完成提議需要另一方在同議題、同版本確認。略過會保留為結果限制。</p>{v.issues.map((issue, index) => <div className={'issue-row' + (issue.id === v.currentIssueId ? ' current' : '')} key={issue.id}><div className="issue-head"><em>{index + 1}</em><strong>{issue.title}</strong><span className={'issue-status ' + issue.status}>{issueStatus[issue.status]}</span><small>v{issue.version}</small></div><div className="actions"><button disabled={busy || !!state.storage} onClick={() => void perform(() => issueAction('select', issue.id))}>選取議題</button><button disabled={busy || !!state.storage} onClick={() => void perform(() => issueAction('skip', issue.id))}>略過議題</button>{issue.source !== 'user' && <button onClick={() => onJump(issue.source)}>來源</button>}</div>{issue.proposal && <p>提議 {issue.proposal.author} · {issueStatus[issue.proposal.outcome]} · 提議 v{issue.proposal.version} · {issue.confirmation ? `已由 ${issue.confirmation.author} 確認` : '待另一方確認'} <button onClick={() => onJump(issue.proposal!.messageId)}>查看提議</button></p>}{issue.result && <p>{issue.result}</p>}{issue.proposal?.conditions && <p>適用條件／分歧依據：{issue.proposal.conditions}</p>}{issue.unresolved.length > 0 && <p>未解：{issue.unresolved.join('；')}</p>}</div>)}
      <dl className="run-summary"><dt>已進行</dt><dd>第 {state.round} / {state.limits.maxRounds} 輪</dd><dt>執行時間</dt><dd>{durationText(state.elapsedMs)} / {durationText(state.limits.maxDurationMs)}</dd><dt>單次上限</dt><dd>{durationText(state.limits.turnTimeoutMs)}</dd><dt>執行模式</dt><dd>{{ manual: '手動', auto: '自動', conclusion: '有結論就停' }[state.mode]} · {state.flow === 'free' ? '自由對話' : '輪流發言'}</dd></dl>
      <form onSubmit={e => { e.preventDefault(); void perform(async () => { await issueAction('add', crypto.randomUUID(), title); setTitle(''); }); }}><label>新增待討論議題<input aria-label="新增議題" required maxLength={32000} value={title} onChange={e => setTitle(e.target.value)}/></label><button disabled={busy || !!state.storage || !title.trim()}>加入待討論</button></form>
      <form onSubmit={e => { e.preventDefault(); void perform(() => api(`/api/discussions/${state.id}`, 'PATCH', { expectedVersion: v.configurationVersion, goal, constraints })); }}><label>目前目標<textarea aria-label="目前目標" value={goal} maxLength={32000} onChange={e => setGoal(e.target.value)}/></label><label>目前限制<textarea aria-label="目前限制" value={constraints} maxLength={32000} onChange={e => setConstraints(e.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={state.focused} disabled={busy || !!state.storage} onChange={e => void perform(() => api(`/api/discussions/${state.id}`, 'PATCH', { expectedVersion: v.configurationVersion, focused: e.target.checked }))}/>聚焦討論</label><button disabled={busy || !!state.storage}>更新目標與限制</button></form>
      <p>未處置要求</p>{v.requests.filter(r => !['disposed', 'checked'].includes(r.status)).map(r => <div key={r.messageId}><button onClick={() => onJump(r.messageId)}>查看使用者要求</button> · {r.status === 'unmarked' ? '未標註' : '已標註回應 · 尚待檢查'} {r.reason}<button disabled={busy || !!state.storage} onClick={() => void perform(() => issueAction('dispose', r.messageId, 'User marked this request as disposed.'))}>我已處置此要求</button></div>)}
    </details>}
    {section === 'diagnostics' && <PerformancePanel discussionId={state.id}/>}
    {section === 'diagnostics' && <details open><summary>輸入與呼叫診斷 · {v.calls.length} 次</summary><p>曾納入 session 不表示模型完整保有細節。未觀測時間及未回傳 token 用量顯示未知；不推估帳單。無法確認耗時的中斷呼叫，已保守保留 {v.uncertainBudgetMs} ms 執行預算；這不是觀測耗時。</p>{v.receipts.map(r => <p key={r.generation}>{r.agent} · {r.status} · {r.messages.length} 則已納入 · {r.evidence.length} 個來源版本 · 設定 v{r.configurationVersion} · {r.sessionId ?? '暫定工作階段'}</p>)}{v.calls.map(call => <details key={call.requestId}><summary>{call.agent} · {call.status} · {call.diagnostics.input.characters.toLocaleString()} 字元 · 控制 {call.control ?? '未確認'}</summary><p>回應標註：{call.annotation} · 回應對象 {call.snapshot.responseTarget ? <button onClick={() => onJump(call.snapshot.responseTarget!)}>來源訊息</button> : '無'}</p><pre>{JSON.stringify({ requestId: call.requestId, generation: call.snapshot.generation, resolvedModel: call.resolvedModel, input: call.diagnostics.input,
        timings: call.diagnostics.timings, usage: call.diagnostics.usage ?? 'unknown', failureStage: call.diagnostics.failureStage }, null, 2)}</pre></details>)}</details>}
  </div>;
}
