import { createRoot } from 'react-dom/client';
import { App } from './App';
import { getLocale, setLocale } from './i18n.js';
import './styles/tokens.css';
import './styles/base.css';
import './styles/attachments.css';
import './styles/components.css';
import './styles/shell.css';
import './styles/history.css';
import './styles/conversation.css';
import './styles/new-discussion.css';
import './styles/seats.css';
import './styles/room.css';
import './styles/bubbles.css';
import './styles/result.css';
import './styles/create.css';
import './ui/picker.css';
import './styles/polish.css';
import './reading.css';
const savedTheme = localStorage.getItem('candc-theme');
document.documentElement.dataset.theme = savedTheme === 'dark' || (savedTheme !== 'light' && matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light';
const savedSize = localStorage.getItem('candc-font-size') ?? '16';
document.documentElement.style.setProperty('--reading-size', `${['14', '16', '18'].includes(savedSize) ? savedSize : '16'}px`);
document.documentElement.dataset.density = localStorage.getItem('candc-density') === 'compact' ? 'compact' : 'comfortable';
setLocale(getLocale());
createRoot(document.getElementById('root')!).render(<App />);
